name: Build, Test and Deploy ASP.Net Core app to Azure Web App - BluePath

on:
  push:
    branches:
      - Development
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Zet juiste versie

      - name: Restore dependencies
        run: dotnet restore BluePathBackend/BluePathBackend.sln

      - name: Build project
        run: dotnet build BluePathBackend/BluePathBackend.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test BluePathBackend/BluePathBackend.sln --no-build --verbosity normal

      - name: Publish app
        run: dotnet publish BluePathBackend/BluePathBackend.csproj -c Release -o publish

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: publish

  deploy:
    runs-on: windows-latest
    needs: build_and_test
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BluePath'
          slot-name: 'Production'
          package: .
