name: Build, test and deploy ASP.Net Core app to Azure Web App - BluePath

on:
  push:
    branches:
      - Development
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build BluePathBackend/BluePathBackend.sln --configuration Release

      - name: Publish with dotnet
        run: dotnet publish BluePathBackend/BluePathBackend/BluePathBackend.csproj -c Release -o publish_output

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: publish_output

- name: Download artifact from build job
  uses: actions/download-artifact@v4
  with:
    name: .net-app
    path: ./publish_output

- name: Login to Azure
  uses: azure/login@v2
  with:
    client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4EEAB572575A4789865B0C7B0E35840A }}
    tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B4AED12824014DE3971FBF0732BB8F9F }}
    subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_06516DFC7A26473BA048B0F4ED68F898 }}

- name: Set Azure App Settings
  uses: azure/appservice-settings@v2
  with:
    app-name: 'BluePath'
    settings-json: |
      {
        "ConnectionStrings__SqlConnectionString": "${{ secrets.SQLCONNECTIONSTRING }}",
        "Jwt__Key": "${{ secrets.JWT_KEY }}"
      }

- name: Deploy to Azure Web App
  id: deploy-to-webapp
  uses: azure/webapps-deploy@v3
  with:
    app-name: 'BluePath'
    slot-name: 'Production'
    package: ./publish_output

